In [1]:
import pandas as pd 
import numpy as np

df_Vendas = pd.read_csv("vendas.csv" , sep = ";")
df_Gerente = pd.read_excel("gerentes_lojas.xlsx")

DIPLAY BASES

In [2]:
display(df_Vendas.sample(15))

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario
3085,3086,104,Mesa de Escritório,Móveis,2026-01-19,9.0,"R$ 1702,22"
3969,3970,104,Carregador,Acessórios,2026-01-16,NaN,"R$ 257,56"
3818,3819,105,Mousepad,Periféricos,2026-02-03,9.0,"R$ 296,54"
4889,4890,105,carregador,Acessórios,2026-01-22,10.0,"R$ 143,4"
4822,4823,104,Cabo HDMI,Acessórios,2026-03-13,3.0,"R$ 154,09"
568,569,101,Mousepad,Periféricos,2026-03-15,2.0,"R$ 258,47"
1759,1760,101,Carregador,Acessórios,2026-03-04,3.0,"R$ 318,66"
3950,3951,105,mesa de escritório,Móveis,2026-03-25,5.0,"R$ 1132,84"
3205,3206,105,Smart TV,Eletrônicos,2026-01-28,7.0,"R$ 4134,48"
3600,3601,101,Mouse,Periféricos,2026-03-22,7.0,"R$ 31,9"
1758,1759,104,Cadeira Gamer,Móveis,2026-01-14,NaN,"R$ 926,47"
3022,3023,102,Filtro de Linha,Acessórios,2026-02-06,7.0,"R$ 282,64"
1948,1949,102,Gaveteiro,Móveis,2026-01-03,NaN,"R$ 2486,11"
4046,4047,104,Smartphone,Eletrônicos,2026-02-04,9.0,"R$ 4442,51"
3819,3820,104,Mouse,Periféricos,2026-01-22,3.0,"R$ 174,98"

In [3]:
display(df_Vendas.tail(10))

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario
4990,4991,105,teclado,Periféricos,2026-02-08,1.0,"R$ 69,06"
4991,4992,101,Monitor,Eletrônicos,2026-01-15,9.0,"R$ 5209,75"
4992,4993,102,Cadeira Gamer,Móveis,2026-03-19,8.0,"R$ 1547,78"
4993,4994,102,Gaveteiro,Móveis,2026-01-21,8.0,"R$ 2494,33"
4994,4995,105,Gaveteiro,Móveis,2026-03-16,7.0,"R$ 928,93"
4995,4996,105,Carregador,NaN,2026-03-12,4.0,"R$ 144,07"
4996,4997,104,Smart TV,Eletrônicos,2026-01-13,4.0,"R$ 5011,78"
4997,4998,102,Câmera,Eletrônicos,2026-02-14,8.0,"R$ 4745,72"
4998,4999,102,Filtro de Linha,Acessórios,2026-03-05,5.0,"R$ 126,01"
4999,5000,104,filtro de linha,Acessórios,2026-03-24,3.0,"R$ 248,1"

In [4]:
display(df_Gerente)
display(df_Vendas.head(10))

   ID_Loja  Regiao     Nome_Gerente  Meta_Mensal
0      101   Norte     Carlos Silva        50000
1      102     Sul        Ana Souza        75000
2      103   Leste  Marcos Oliveira        60000
3      104   Oeste    Juliana Costa        45000
4      105  Centro  Ricardo Almeida        80000

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario
0,1,101,Câmera,Eletrônicos,2026-02-08,4.0,"R$ 1455,83"
1,2,105,Cabo HDMI,Acessórios,2026-01-03,4.0,"R$ 96,78"
2,3,105,Filtro de Linha,Acessórios,2026-02-19,NaN,"R$ 287,11"
3,4,103,Mesa de Escritório,Móveis,2026-01-25,6.0,"R$ 524,86"
4,5,103,Câmera,Eletrônicos,2026-02-18,2.0,"R$ 5373,64"
5,6,105,Mesa de Escritório,Móveis,2026-03-03,1.0,"R$ 1754,78"
6,7,101,Hub USB,Acessórios,2026-02-21,6.0,"R$ 73,68"
7,8,101,Webcam,Periféricos,2026-03-08,3.0,"R$ 172,55"
8,9,102,Cadeira Gamer,Móveis,2026-01-27,1.0,"R$ 2071,1"
9,10,105,mesa de escritório,Móveis,2026-03-16,7.0,"R$ 2246,3"

In [5]:
display(list(df_Vendas.head(50)))

['ID_Venda',
 'ID_Loja',
 'Produto',
 'Categoria',
 'Data_Venda',
 'Qtd',
 'Valor_Unitario']

In [6]:
display(df_Vendas.describe())

          ID_Venda      ID_Loja          Qtd
count  5000.000000  5000.000000  4525.000000
mean   2500.500000   103.003000     5.463646
std    1443.520003     1.411449     2.910212
min       1.000000   101.000000     1.000000
25%    1250.750000   102.000000     3.000000
50%    2500.500000   103.000000     6.000000
75%    3750.250000   104.000000     8.000000
max    5000.000000   105.000000    10.000000

In [7]:
display(df_Vendas.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        5000 non-null   int64
 1   ID_Loja         5000 non-null   int64
 2   Produto         5000 non-null   str
 3   Categoria       4753 non-null   str
 4   Data_Venda      5000 non-null   str
 5   Qtd             4525 non-null   float64
 6   Valor_Unitario  5000 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 273.6 KB

None

TRATAMENTOS DE DADOS

In [8]:

display(df_Vendas["Categoria"])
display(df_Vendas[["Produto" , "Valor_Unitario"]].sample(15))

0       Eletrônicos
1        Acessórios
2        Acessórios
3            Móveis
4       Eletrônicos
           ...
4995            NaN
4996    Eletrônicos
4997    Eletrônicos
4998     Acessórios
4999     Acessórios
Name: Categoria, Length: 5000, dtype: str

                 Produto Valor_Unitario
203               Webcam      R$ 349,38
2569          Carregador      R$ 266,26
1816  Mesa de Escritório     R$ 1971,44
1487          Smartphone     R$ 1784,44
2100            Mousepad      R$ 282,16
4301           hub usb        R$ 307,65
4705            webcam         R$ 91,06
3935            Notebook     R$ 1520,41
1670       Cadeira Gamer      R$ 538,63
4392              Câmera      R$ 3453,9
4088              Câmera     R$ 1455,64
4458           Gaveteiro      R$ 556,91
4581             Monitor     R$ 3137,02
947             Mousepad       R$ 39,41
4677     Filtro de Linha       R$ 39,96

In [9]:
df_analise = df_Vendas

In [10]:
df_t = df_analise.dropna()
display(df_t.info())

<class 'pandas.DataFrame'>
Index: 4300 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        4300 non-null   int64
 1   ID_Loja         4300 non-null   int64
 2   Produto         4300 non-null   str
 3   Categoria       4300 non-null   str
 4   Data_Venda      4300 non-null   str
 5   Qtd             4300 non-null   float64
 6   Valor_Unitario  4300 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 268.8 KB

None

In [11]:
df_t = df_analise.fillna("0").sample(15)
display(df_t)

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario
2799,2800,105,Tablet,Eletrônicos,2026-03-12,2.0,"R$ 3890,58"
2617,2618,104,Teclado,Periféricos,2026-02-08,10.0,"R$ 56,61"
4061,4062,105,mesa de escritório,Móveis,2026-02-21,2.0,"R$ 527,84"
2625,2626,103,Mouse,Periféricos,2026-01-11,0,"R$ 44,65"
3506,3507,103,Gaveteiro,Móveis,2026-02-09,4.0,"R$ 769,77"
4085,4086,105,Capa Protetora,Acessórios,2026-02-24,5.0,"R$ 178,86"
1112,1113,101,Mesa de Escritório,Móveis,2026-01-18,2.0,"R$ 906,01"
3523,3524,102,Hub USB,Acessórios,2026-03-17,2.0,"R$ 47,44"
2091,2092,103,Mesa de Escritório,Móveis,2026-03-02,3.0,"R$ 911,59"
352,353,102,capa protetora,Acessórios,2026-03-24,9.0,"R$ 107,54"
3728,3729,103,Mouse,Periféricos,2026-01-06,8.0,"R$ 267,24"
478,479,102,Capa Protetora,Acessórios,2026-01-18,2.0,"R$ 186,05"
50,51,104,Teclado,Periféricos,2026-03-23,1.0,"R$ 314,58"
2205,2206,104,Mousepad,Periféricos,2026-01-28,9.0,"R$ 307,88"
3434,3435,104,Microfone,Periféricos,2026-02-10,4.0,"R$ 209,01"

In [12]:
df_analise["Data_Venda"] = pd.to_datetime(df_analise["Data_Venda"] , format="%Y-%m-%d")
df_analise.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        5000 non-null   int64
 1   ID_Loja         5000 non-null   int64
 2   Produto         5000 non-null   str
 3   Categoria       4753 non-null   str
 4   Data_Venda      5000 non-null   datetime64[us]
 5   Qtd             4525 non-null   float64
 6   Valor_Unitario  5000 non-null   str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 273.6 KB

In [13]:
df_analise[["Categoria" , "Produto"]] = df_analise[["Categoria" , "Produto"]].apply(lambda x: x.str.strip().str.title())

In [14]:
df_analise["Valor_Unitario"] = (
    df_analise["Valor_Unitario"]
      .str.replace("R$", "", regex=False)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

OPerações com o Pandas

In [15]:
df_analise["faturamento"] = df_analise["Valor_Unitario"] * df_analise["Qtd"]
display(df_analise.sample(20))

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento
3907,3908,102,Tablet,NaN,2026-01-19,9.0,1633.94,14705.46
2271,2272,104,Mesa De Escritório,Móveis,2026-01-08,6.0,2201.01,13206.06
451,452,105,Webcam,Periféricos,2026-01-15,3.0,79.12,237.36
3538,3539,104,Microfone,Periféricos,2026-01-24,7.0,21.52,150.64
3981,3982,101,Mouse,NaN,2026-01-22,NaN,132.01,NaN
875,876,103,Suporte Monitor,Móveis,2026-03-27,5.0,719.41,3597.05
1768,1769,102,Smart Tv,Eletrônicos,2026-01-11,10.0,2670.27,26702.70
1438,1439,105,Câmera,NaN,2026-03-25,4.0,4412.18,17648.72
65,66,101,Tablet,NaN,2026-03-14,6.0,1124.10,6744.60
2815,2816,103,Teclado,Periféricos,2026-01-04,4.0,196.69,786.76
4498,4499,103,Carregador,Acessórios,2026-01-06,6.0,302.21,1813.26
3498,3499,104,Headset,Periféricos,2026-02-10,3.0,62.33,186.99
2117,2118,105,Microfone,Periféricos,2026-01-03,2.0,78.34,156.68
1806,1807,102,Headset,Periféricos,2026-02-15,6.0,105.91,635.46
2563,2564,101,Hub Usb,Acessórios,2026-03-20,2.0,160.15,320.30
3203,3204,102,Cadeira Gamer,Móveis,2026-01-24,9.0,808.01,7272.09
4263,4264,102,Hub Usb,Acessórios,2026-01-18,8.0,100.81,806.48
1629,1630,105,Smartphone,Eletrônicos,2026-02-15,10.0,3487.92,34879.20
3419,3420,102,Headset,Periféricos,2026-03-07,2.0,31.66,63.32
1878,1879,101,Headset,Periféricos,2026-03-25,10.0,231.23,2312.30

In [16]:
df_analise["Qtd"] = df_analise["Qtd"].fillna(0)

In [17]:
display(df_analise["Qtd"])

0       4.0
1       4.0
2       0.0
3       6.0
4       2.0
       ...
4995    4.0
4996    4.0
4997    8.0
4998    5.0
4999    3.0
Name: Qtd, Length: 5000, dtype: float64

In [18]:
display(sorted(df_analise["Data_Venda"].unique()))
display(df_analise["Categoria"].unique())

[Timestamp('2026-01-01 00:00:00'),
 Timestamp('2026-01-02 00:00:00'),
 Timestamp('2026-01-03 00:00:00'),
 Timestamp('2026-01-04 00:00:00'),
 Timestamp('2026-01-05 00:00:00'),
 Timestamp('2026-01-06 00:00:00'),
 Timestamp('2026-01-07 00:00:00'),
 Timestamp('2026-01-08 00:00:00'),
 Timestamp('2026-01-09 00:00:00'),
 Timestamp('2026-01-10 00:00:00'),
 Timestamp('2026-01-11 00:00:00'),
 Timestamp('2026-01-12 00:00:00'),
 Timestamp('2026-01-13 00:00:00'),
 Timestamp('2026-01-14 00:00:00'),
 Timestamp('2026-01-15 00:00:00'),
 Timestamp('2026-01-16 00:00:00'),
 Timestamp('2026-01-17 00:00:00'),
 Timestamp('2026-01-18 00:00:00'),
 Timestamp('2026-01-19 00:00:00'),
 Timestamp('2026-01-20 00:00:00'),
 Timestamp('2026-01-21 00:00:00'),
 Timestamp('2026-01-22 00:00:00'),
 Timestamp('2026-01-23 00:00:00'),
 Timestamp('2026-01-24 00:00:00'),
 Timestamp('2026-01-25 00:00:00'),
 Timestamp('2026-01-26 00:00:00'),
 Timestamp('2026-01-27 00:00:00'),
 Timestamp('2026-01-28 00:00:00'),
 Timestamp('2026-02-01 00:00:00'),
 Timestamp('2026-02-02 00:00:00'),
 Timestamp('2026-02-03 00:00:00'),
 Timestamp('2026-02-04 00:00:00'),
 Timestamp('2026-02-05 00:00:00'),
 Timestamp('2026-02-06 00:00:00'),
 Timestamp('2026-02-07 00:00:00'),
 Timestamp('2026-02-08 00:00:00'),
 Timestamp('2026-02-09 00:00:00'),
 Timestamp('2026-02-10 00:00:00'),
 Timestamp('2026-02-11 00:00:00'),
 Timestamp('2026-02-12 00:00:00'),
 Timestamp('2026-02-13 00:00:00'),
 Timestamp('2026-02-14 00:00:00'),
 Timestamp('2026-02-15 00:00:00'),
 Timestamp('2026-02-16 00:00:00'),
 Timestamp('2026-02-17 00:00:00'),
 Timestamp('2026-02-18 00:00:00'),
 Timestamp('2026-02-19 00:00:00'),
 Timestamp('2026-02-20 00:00:00'),
 Timestamp('2026-02-21 00:00:00'),
 Timestamp('2026-02-22 00:00:00'),
 Timestamp('2026-02-23 00:00:00'),
 Timestamp('2026-02-24 00:00:00'),
 Timestamp('2026-02-25 00:00:00'),
 Timestamp('2026-02-26 00:00:00'),
 Timestamp('2026-02-27 00:00:00'),
 Timestamp('2026-02-28 00:00:00'),
 Timestamp('2026-03-01 00:00:00'),
 Timestamp('2026-03-02 00:00:00'),
 Timestamp('2026-03-03 00:00:00'),
 Timestamp('2026-03-04 00:00:00'),
 Timestamp('2026-03-05 00:00:00'),
 Timestamp('2026-03-06 00:00:00'),
 Timestamp('2026-03-07 00:00:00'),
 Timestamp('2026-03-08 00:00:00'),
 Timestamp('2026-03-09 00:00:00'),
 Timestamp('2026-03-10 00:00:00'),
 Timestamp('2026-03-11 00:00:00'),
 Timestamp('2026-03-12 00:00:00'),
 Timestamp('2026-03-13 00:00:00'),
 Timestamp('2026-03-14 00:00:00'),
 Timestamp('2026-03-15 00:00:00'),
 Timestamp('2026-03-16 00:00:00'),
 Timestamp('2026-03-17 00:00:00'),
 Timestamp('2026-03-18 00:00:00'),
 Timestamp('2026-03-19 00:00:00'),
 Timestamp('2026-03-20 00:00:00'),
 Timestamp('2026-03-21 00:00:00'),
 Timestamp('2026-03-22 00:00:00'),
 Timestamp('2026-03-23 00:00:00'),
 Timestamp('2026-03-24 00:00:00'),
 Timestamp('2026-03-25 00:00:00'),
 Timestamp('2026-03-26 00:00:00'),
 Timestamp('2026-03-27 00:00:00'),
 Timestamp('2026-03-28 00:00:00')]

<StringArray>
['Eletrônicos', 'Acessórios', 'Móveis', 'Periféricos', nan]
Length: 5, dtype: str

In [19]:
df_analise["Status"] = np.where(df_analise["Categoria"] == "Outros" ,"Incompleto" , "Completo" )
display(df_analise.sample(20))

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status
3346,3347,104,Capa Protetora,Acessórios,2026-02-03,3.0,182.88,548.64,Completo
547,548,101,Câmera,Eletrônicos,2026-01-08,10.0,5155.63,51556.30,Completo
869,870,105,Filtro De Linha,Acessórios,2026-02-23,6.0,193.41,1160.46,Completo
2957,2958,102,Mesa De Escritório,Móveis,2026-01-16,6.0,2273.89,13643.34,Completo
4500,4501,103,Notebook,Eletrônicos,2026-02-24,4.0,5136.80,20547.20,Completo
3800,3801,102,Filtro De Linha,Acessórios,2026-02-03,0.0,190.67,NaN,Completo
2269,2270,105,Capa Protetora,Acessórios,2026-02-26,10.0,116.84,1168.40,Completo
2169,2170,104,Hub Usb,Acessórios,2026-02-16,4.0,272.35,1089.40,Completo
1982,1983,101,Cabo Hdmi,Acessórios,2026-02-08,1.0,230.28,230.28,Completo
1813,1814,102,Suporte Monitor,Móveis,2026-02-14,2.0,1376.03,2752.06,Completo
3432,3433,103,Filtro De Linha,Acessórios,2026-01-18,10.0,138.26,1382.60,Completo
2073,2074,102,Filtro De Linha,Acessórios,2026-03-22,9.0,232.04,2088.36,Completo
1597,1598,105,Cadeira Gamer,Móveis,2026-01-17,4.0,1687.48,6749.92,Completo
1140,1141,103,Carregador,Acessórios,2026-01-27,4.0,297.77,1191.08,Completo
1761,1762,101,Headset,Periféricos,2026-03-14,3.0,208.93,626.79,Completo
4958,4959,105,Mousepad,Periféricos,2026-01-09,4.0,245.87,983.48,Completo
3331,3332,102,Gaveteiro,Móveis,2026-02-01,3.0,1698.95,5096.85,Completo
4748,4749,102,Filtro De Linha,Acessórios,2026-01-23,8.0,92.09,736.72,Completo
1052,1053,104,Webcam,Periféricos,2026-02-28,2.0,93.61,187.22,Completo
3759,3760,104,Cadeira Gamer,Móveis,2026-01-21,1.0,873.72,873.72,Completo

In [20]:
display(df_analise.isna().sum())

ID_Venda            0
ID_Loja             0
Produto             0
Categoria         247
Data_Venda          0
Qtd                 0
Valor_Unitario      0
faturamento       475
Status              0
dtype: int64

In [21]:
display(df_analise["Status"].value_counts())

Status
Completo    5000
Name: count, dtype: int64

Filtrando base de dados

In [22]:
df_analise["Categoria"] = df_analise["Categoria"].fillna("Outros")
display(df_analise[["Categoria"]].sample(15))

        Categoria
2486  Periféricos
1515  Eletrônicos
2719       Móveis
2600       Móveis
1476       Móveis
1375  Periféricos
1967  Eletrônicos
1293       Móveis
1550  Periféricos
541   Eletrônicos
1901  Eletrônicos
3036       Móveis
1707  Periféricos
1943       Móveis
4514   Acessórios

In [23]:
display(df_analise["Categoria"].unique())

<StringArray>
['Eletrônicos', 'Acessórios', 'Móveis', 'Periféricos', 'Outros']
Length: 5, dtype: str

In [24]:
display(df_analise[["Categoria"]].drop_duplicates())

      Categoria
0   Eletrônicos
1    Acessórios
3        Móveis
7   Periféricos
61       Outros

Mapeando colunas

In [25]:
regras_setor = {
    "Eletrônicos": "Tecnologia",
    "Periféricos": "Tecnologia",
    "Acessórios": "Diversos",
    "Móveis": "Decoração e Casa",
    "Outros": "Diversos"
}

df_analise["Setor"] = df_analise["Categoria"].map(regras_setor)

In [26]:
display(df_analise)

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
0,1,101,Câmera,Eletrônicos,2026-02-08,4.0,1455.83,5823.32,Completo,Tecnologia
1,2,105,Cabo Hdmi,Acessórios,2026-01-03,4.0,96.78,387.12,Completo,Diversos
2,3,105,Filtro De Linha,Acessórios,2026-02-19,0.0,287.11,NaN,Completo,Diversos
3,4,103,Mesa De Escritório,Móveis,2026-01-25,6.0,524.86,3149.16,Completo,Decoração e Casa
4,5,103,Câmera,Eletrônicos,2026-02-18,2.0,5373.64,10747.28,Completo,Tecnologia
...,...,...,...,...,...,...,...,...,...,...
4995,4996,105,Carregador,Outros,2026-03-12,4.0,144.07,576.28,Completo,Diversos
4996,4997,104,Smart Tv,Eletrônicos,2026-01-13,4.0,5011.78,20047.12,Completo,Tecnologia
4997,4998,102,Câmera,Eletrônicos,2026-02-14,8.0,4745.72,37965.76,Completo,Tecnologia
4998,4999,102,Filtro De Linha,Acessórios,2026-03-05,5.0,126.01,630.05,Completo,Diversos
4999,5000,104,Filtro De Linha,Acessórios,2026-03-24,3.0,248.10,744.30,Completo,Diversos

In [27]:

df_analise = df_analise.reset_index(drop= True)

In [28]:
Eletrônicos = df_analise[df_analise["Categoria"]== "Eletrônicos"]
Acessórios = df_analise[df_analise["Categoria"]== "Acessórios"]
Moveis = df_analise[df_analise["Categoria"]== "Móveis"]
Periféricos = df_analise[df_analise["Categoria"]== "Periféricos"]
Outros = df_analise[df_analise["Categoria"]== "Outros"]

display(Eletrônicos.head())
display(Acessórios.head())
display(Moveis.head())
display(Periféricos.head())
display(Outros.head())

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
0,1,101,Câmera,Eletrônicos,2026-02-08,4.0,1455.83,5823.32,Completo,Tecnologia
4,5,103,Câmera,Eletrônicos,2026-02-18,2.0,5373.64,10747.28,Completo,Tecnologia
11,12,101,Monitor,Eletrônicos,2026-03-06,7.0,3603.12,25221.84,Completo,Tecnologia
12,13,103,Câmera,Eletrônicos,2026-03-04,9.0,4329.13,38962.17,Completo,Tecnologia
16,17,104,Smart Tv,Eletrônicos,2026-01-05,8.0,5250.19,42001.52,Completo,Tecnologia

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
1,2,105,Cabo Hdmi,Acessórios,2026-01-03,4.0,96.78,387.12,Completo,Diversos
2,3,105,Filtro De Linha,Acessórios,2026-02-19,0.0,287.11,NaN,Completo,Diversos
6,7,101,Hub Usb,Acessórios,2026-02-21,6.0,73.68,442.08,Completo,Diversos
13,14,102,Cabo Hdmi,Acessórios,2026-03-24,5.0,340.72,1703.60,Completo,Diversos
15,16,103,Cabo Hdmi,Acessórios,2026-01-12,5.0,99.02,495.10,Completo,Diversos

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
3,4,103,Mesa De Escritório,Móveis,2026-01-25,6.0,524.86,3149.16,Completo,Decoração e Casa
5,6,105,Mesa De Escritório,Móveis,2026-03-03,1.0,1754.78,1754.78,Completo,Decoração e Casa
8,9,102,Cadeira Gamer,Móveis,2026-01-27,1.0,2071.10,2071.10,Completo,Decoração e Casa
9,10,105,Mesa De Escritório,Móveis,2026-03-16,7.0,2246.30,15724.10,Completo,Decoração e Casa
10,11,105,Gaveteiro,Móveis,2026-03-13,6.0,782.51,4695.06,Completo,Decoração e Casa

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
7,8,101,Webcam,Periféricos,2026-03-08,3.0,172.55,517.65,Completo,Tecnologia
14,15,103,Teclado,Periféricos,2026-02-25,3.0,198.00,594.00,Completo,Tecnologia
17,18,102,Microfone,Periféricos,2026-02-13,6.0,164.57,987.42,Completo,Tecnologia
22,23,102,Webcam,Periféricos,2026-02-05,7.0,80.55,563.85,Completo,Tecnologia
29,30,103,Headset,Periféricos,2026-02-05,5.0,170.88,854.40,Completo,Tecnologia

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
61,62,102,Câmera,Outros,2026-01-25,1.0,5263.18,5263.18,Completo,Diversos
65,66,101,Tablet,Outros,2026-03-14,6.0,1124.10,6744.60,Completo,Diversos
95,96,103,Microfone,Outros,2026-01-19,7.0,97.08,679.56,Completo,Diversos
165,166,105,Smartphone,Outros,2026-02-02,7.0,5410.89,37876.23,Completo,Diversos
169,170,105,Hub Usb,Outros,2026-01-25,4.0,114.42,457.68,Completo,Diversos

Filtrando com condições

In [29]:
faturamentoGrande = df_analise[df_analise["faturamento"]>=3000]
display(faturamentoGrande)

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
0,1,101,Câmera,Eletrônicos,2026-02-08,4.0,1455.83,5823.32,Completo,Tecnologia
3,4,103,Mesa De Escritório,Móveis,2026-01-25,6.0,524.86,3149.16,Completo,Decoração e Casa
4,5,103,Câmera,Eletrônicos,2026-02-18,2.0,5373.64,10747.28,Completo,Tecnologia
9,10,105,Mesa De Escritório,Móveis,2026-03-16,7.0,2246.30,15724.10,Completo,Decoração e Casa
10,11,105,Gaveteiro,Móveis,2026-03-13,6.0,782.51,4695.06,Completo,Decoração e Casa
...,...,...,...,...,...,...,...,...,...,...
4992,4993,102,Cadeira Gamer,Móveis,2026-03-19,8.0,1547.78,12382.24,Completo,Decoração e Casa
4993,4994,102,Gaveteiro,Móveis,2026-01-21,8.0,2494.33,19954.64,Completo,Decoração e Casa
4994,4995,105,Gaveteiro,Móveis,2026-03-16,7.0,928.93,6502.51,Completo,Decoração e Casa
4996,4997,104,Smart Tv,Eletrônicos,2026-01-13,4.0,5011.78,20047.12,Completo,Tecnologia
4997,4998,102,Câmera,Eletrônicos,2026-02-14,8.0,4745.72,37965.76,Completo,Tecnologia

In [30]:
cond1 = df_analise["Data_Venda"]>="2026-01-25"
cond2 = df_analise["faturamento"]>= 1000
df_data = df_analise[cond1 & cond2]
display(df_data)

,ID_Venda,ID_Loja,Produto,Categoria,Data_Venda,Qtd,Valor_Unitario,faturamento,Status,Setor
0,1,101,Câmera,Eletrônicos,2026-02-08,4.0,1455.83,5823.32,Completo,Tecnologia
3,4,103,Mesa De Escritório,Móveis,2026-01-25,6.0,524.86,3149.16,Completo,Decoração e Casa
4,5,103,Câmera,Eletrônicos,2026-02-18,2.0,5373.64,10747.28,Completo,Tecnologia
5,6,105,Mesa De Escritório,Móveis,2026-03-03,1.0,1754.78,1754.78,Completo,Decoração e Casa
8,9,102,Cadeira Gamer,Móveis,2026-01-27,1.0,2071.10,2071.10,Completo,Decoração e Casa
...,...,...,...,...,...,...,...,...,...,...
4987,4988,102,Cadeira Gamer,Móveis,2026-03-26,2.0,2159.29,4318.58,Completo,Decoração e Casa
4989,4990,101,Cadeira Gamer,Móveis,2026-03-25,3.0,1699.23,5097.69,Completo,Decoração e Casa
4992,4993,102,Cadeira Gamer,Móveis,2026-03-19,8.0,1547.78,12382.24,Completo,Decoração e Casa
4994,4995,105,Gaveteiro,Móveis,2026-03-16,7.0,928.93,6502.51,Completo,Decoração e Casa
4997,4998,102,Câmera,Eletrônicos,2026-02-14,8.0,4745.72,37965.76,Completo,Tecnologia

Analise com Agrupamento

In [31]:
categoria_faturamento = df_analise[["Categoria" , "faturamento"]].groupby("Categoria").sum()
categoria_faturamento = categoria_faturamento.sort_values("faturamento" , ascending= False)
categoria_faturamento = categoria_faturamento.rename(columns= {"faturamento": "valor_total"})

display(categoria_faturamento)

             valor_total
Categoria
Eletrônicos  18583946.75
Móveis        7990231.08
Outros        1488810.05
Acessórios    1124937.12
Periféricos   1069368.58

analise de agrupamento com 3 variaveis

In [33]:
categoria_prod_fat = df_analise[["Categoria" , "Produto" , "faturamento"]].groupby(["Categoria" , "Produto"],as_index= False ).sum()
categoria_prod_fat = categoria_prod_fat.sort_values( ["Categoria", "faturamento"] , ascending= False)



display(categoria_prod_fat)

      Categoria             Produto  faturamento
39  Periféricos            Mousepad    204948.18
38  Periféricos               Mouse    194578.65
37  Periféricos           Microfone    180324.29
40  Periféricos             Teclado    166945.80
36  Periféricos             Headset    163019.50
41  Periféricos              Webcam    159552.16
31       Outros          Smartphone    260858.17
26       Outros             Monitor    190484.30
33       Outros              Tablet    170781.28
29       Outros            Notebook    148198.84
30       Outros            Smart Tv    139980.91
21       Outros           Gaveteiro    138025.04
19       Outros              Câmera    124657.10
24       Outros  Mesa De Escritório     82295.35
32       Outros     Suporte Monitor     77070.73
16       Outros       Cadeira Gamer     49060.11
34       Outros             Teclado     13992.10
18       Outros          Carregador     13953.65
15       Outros           Cabo Hdmi     12593.78
25       Outros           Microfone     11497.71
35       Outros              Webcam      9807.86
20       Outros     Filtro De Linha      9423.43
23       Outros             Hub Usb      9235.53
22       Outros             Headset      8603.72
28       Outros            Mousepad      8437.62
27       Outros               Mouse      5277.93
17       Outros      Capa Protetora      4574.89
12       Móveis           Gaveteiro   2236428.32
13       Móveis  Mesa De Escritório   2097534.82
11       Móveis       Cadeira Gamer   1830346.99
14       Móveis     Suporte Monitor   1825920.95
5   Eletrônicos              Câmera   3754317.92
8   Eletrônicos            Smart Tv   3335260.56
10  Eletrônicos              Tablet   3162502.03
6   Eletrônicos             Monitor   3119600.28
9   Eletrônicos          Smartphone   2643024.55
7   Eletrônicos            Notebook   2569241.41
4    Acessórios             Hub Usb    236124.85
3    Acessórios     Filtro De Linha    235841.97
2    Acessórios          Carregador    230279.17
0    Acessórios           Cabo Hdmi    217182.21
1    Acessórios      Capa Protetora    205508.92

usando Joins no Pandas

In [50]:
df_meta = df_analise[df_analise["Data_Venda"].dt.month == 3]
df_meta = df_meta[["ID_Loja" , "faturamento"]].groupby("ID_Loja" , as_index=False).sum()
df_meta = df_meta.merge(df_Gerente , on= "ID_Loja" , how="left" )
df_meta["Meta_comprida?"] = np.where(df_meta["faturamento"]>= df_meta["Meta_Mensal"] , "Sim" , "Não")
display(df_meta)

   ID_Loja  faturamento  Regiao     Nome_Gerente  Meta_Mensal Meta_comprida?
0      101   2204158.23   Norte     Carlos Silva        50000            Sim
1      102   1731783.55     Sul        Ana Souza        75000            Sim
2      103   1897946.01   Leste  Marcos Oliveira        60000            Sim
3      104   2130636.59   Oeste    Juliana Costa        45000            Sim
4      105   2404240.83  Centro  Ricardo Almeida        80000            Sim

In [51]:
df_analise["mes_ano"] = df_analise["Data_Venda"].dt.to_period("M")
Mes_ano = df_analise[["mes_ano" , "faturamento"]].groupby("mes_ano").sum()
display(Mes_ano)

         faturamento
mes_ano
2026-01   9979001.33
2026-02   9909527.04
2026-03  10368765.21